---
#infra itescia 
- name: "configuration general"
  hosts: all
  become: true
  vars:
    list_users:
      - toto
      - titi
      - tata
#    ansible_user: itesciaadmin
  tasks:
  - name: "creation users adminitescia"
    user: 
      name: adminitescia
      create_home: yes
      shell: /bin/bash      

  - name: "déployage des packages htop+vim"
    package:
      name: htop
      state: present

  - name: "Création clé ssh pour"
    authorized_key:
      user: adminitescia
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
